apiVersion: v1
kind: ConfigMap
metadata:
  name: elk-exporter-configs
data:
  filebeat.yml: |-
    filebeat.config:
      inputs:
        path: /var/log/log.txt
        reload.enabled: true
    
    processors:
      - add_cloud_metadata: ~
      - drop_fields:
          when:
            has_fields: [ 'kubernetes.labels.app' ]
          fields:
            - 'kubernetes.labels.app'
    
    output.elasticsearch:
      hosts: [ '${ELASTICSEARCH_HOST:elasticsearch}:${ELASTICSEARCH_PORT:9200}' ]